### ISSUE TITLE
No sequencing summary file found using docker execution

### ISSUE THREAD

**Issue by fanavarro** [WGLab/DeepRepeat#9]
Hi, I am trying to use DeepRepeat through docker, so I have followed the instructions in the readme to do that.

Nonetheless, I am receiving an error indicating the following:

```
Error happen!
	 data/LSA-2022-0019/test/sequencing_summary.txt does not exist. Should specified by --summary_file.
```
Actually, I am setting the summary file by using --summary_file option. The file exists, so I can do "cat data/LSA-2022-0019/test/sequencing_summary.txt" to see its content.

I am wondering if this issue could be related to Docker. Should I include the file inside the docker container? Or is it fine to have it in my filesystem?

Thanks beforehand!

**Comment by fanavarro** [comment]
I am answering myself after reading other issue... Yes, I have to map my working directory into the container when running the docker command. Something like:

`docker run -v "MY_WORK_DIR":/workspace/ --rm genomicslab/deeprepeat:0.1.3 python DeepRepeat.py Detect`

And then specify the parameters by assuming the root "/workspace".

**Comment by liuqianhn** [comment]
@fanavarro Glad that you solved the issue. Yes, you need to map local folder to docker folder.
